In [5]:
import warnings
import time
from timeit import default_timer as timer

warnings.filterwarnings("ignore")

In [6]:
from collections import OrderedDict
from functools import partial
from timeit import default_timer as timer
from dataclasses import dataclass
import typing
from flytekit import Resources, task, workflow, dynamic
from flytekit.types.file import FlyteFile
from flytekit.types.schema import FlyteSchema
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import xgboost

### Common part: global variables

In [7]:
DATASET_PATH = "santander_train.csv"
ETL_KEYS = ["t_readcsv", "t_etl", "t_connect"]
ML_KEYS = ["t_train_test_split", "t_dmatrix", "t_training", "t_infer", "t_ml"]
ML_SCORE_KEYS = ["mse_mean", "cod_mean", "mse_dev"]

VAR_COLS = ["var_%s" % i for i in range(200)]
COLUMNS_NAMES = ["ID_code", "target"] + VAR_COLS
COLUMNS_TYPES = ["object", "int64"] + ["float64" for _ in range(200)]

### Workflow consisting from 2 tasks

In [4]:
# from utils

def load_data_pandas(
    filename,
    columns_names=None,
    columns_types=None,
    header=None,
    nrows=None,
    use_gzip=False,
    parse_dates=None
):
    types = None
    if columns_types:
        types = {columns_names[i]: columns_types[i] for i in range(len(columns_names))}
    return pd.read_csv(
        filename,
        names=columns_names,
        nrows=nrows,
        header=header,
        dtype=types,
        compression="gzip" if use_gzip else None,
        parse_dates=parse_dates,
    )

In [5]:
def mse(y_test, y_pred):
    return ((y_test - y_pred) ** 2).mean()


def cod(y_test, y_pred):
    y_bar = y_test.mean()
    total = ((y_test - y_bar) ** 2).sum()
    residuals = ((y_test - y_pred) ** 2).sum()
    return 1 - (residuals / total)

In [6]:
def split_step(data, target):
    t0 = timer()
    train, valid = data[:-10000], data[-10000:]
    split_time = timer() - t0

    x_train = train.drop([target], axis=1)

    y_train = train[target]

    x_test = valid.drop([target], axis=1)

    y_test = valid[target]

    return (x_train, y_train, x_test, y_test), split_time

In [7]:
@task
def etl_pandas(
    filename: str,
    columns_names: typing.List[str],
    columns_types: typing.List[str],
    etl_keys: typing.List[str]
) -> (
    pd.DataFrame,
    typing.Dict[str, float]
):
    etl_times = {key: 0.0 for key in etl_keys}

    t0 = timer()
    train_pd = load_data_pandas(
        filename=filename,
        columns_names=columns_names,
        columns_types=columns_types,
        header=0,
        use_gzip=filename.endswith(".gz")
    )
    etl_times["t_readcsv"] = timer() - t0

    t_etl_begin = timer()

    for i in range(200):
        col = "var_%d" % i
        var_count = train_pd.groupby(col).agg({col: "count"})

        var_count.columns = ["%s_count" % col]
        var_count = var_count.reset_index()

        train_pd = train_pd.merge(var_count, on=col, how="left")

    for i in range(200):
        col = "var_%d" % i

        mask = train_pd["%s_count" % col] > 1
        train_pd.loc[mask, "%s_gt1" % col] = train_pd.loc[mask, col]

    train_pd = train_pd.drop(["ID_code"], axis=1)
    etl_times["t_etl"] = timer() - t_etl_begin

    return train_pd, etl_times

In [8]:
@task
def ml(
    ml_data: pd.DataFrame,
    target: str,
    ml_keys: typing.List[str],
    ml_score_keys: typing.List[str] 
) -> (
    typing.Dict[str, float],
     typing.Dict[str, float]
):

    ml_times = {key: 0.0 for key in ml_keys}
    ml_scores = {key: 0.0 for key in ml_score_keys}

    (x_train, y_train, x_test, y_test), ml_times["t_train_test_split"] = split_step(
        ml_data, target
    )

    t0 = timer()
    training_dmat_part = xgboost.DMatrix(data=x_train, label=y_train)
    testing_dmat_part = xgboost.DMatrix(data=x_test, label=y_test)
    ml_times["t_dmatrix"] = timer() - t0

    watchlist = [(testing_dmat_part, "eval"), (training_dmat_part, "train")]
    #     hard_code: cpu_params cannot be an input, cause values are not homogeneous
    xgb_params = {
        "objective": "binary:logistic",
        "tree_method": "hist",
        "max_depth": 1,
        "nthread": 56,
        "eta": 0.1,
        "silent": 1,
        "subsample": 0.5,
        "colsample_bytree": 0.05,
        "eval_metric": "auc",
    }

    t0 = timer()
    model = xgboost.train(
        xgb_params,
        dtrain=training_dmat_part,
        num_boost_round=10000,
        evals=watchlist,
        early_stopping_rounds=30,
        maximize=True,
        verbose_eval=1000,
    )
    ml_times["t_train"] = timer() - t0

    t0 = timer()
    yp = model.predict(testing_dmat_part)
    ml_times["t_inference"] = timer() - t0

    ml_scores["mse"] = mse(y_test, yp)
    ml_scores["cod"] = cod(y_test, yp)

    ml_times["t_ml"] += ml_times["t_train"] + ml_times["t_inference"]

    return ml_scores, ml_times

In [9]:
@workflow
def santander_ml_wf(
    filename: str = DATASET_PATH,
    columns_names: typing.List[str] = COLUMNS_NAMES,
    columns_types: typing.List[str] = COLUMNS_TYPES,
    etl_keys: typing.List[str] = ETL_KEYS,
    target: str = 'target',
    ml_keys: typing.List[str] = ML_KEYS,
    ml_score_keys: typing.List[str] = ML_SCORE_KEYS
) -> (
    typing.Dict[str, float],
     typing.Dict[str, float]
):
    df, etl_times = etl_pandas(filename=filename, columns_names=columns_names,
                               columns_types=columns_types, etl_keys=etl_keys)
    return ml(ml_data=df, target=target, ml_keys=ml_keys, ml_score_keys=ml_score_keys)

In [10]:
if __name__ == "__main__":
    start = time.time()
    print(santander_ml_wf())
    print("--- %s seconds ---" % (time.time() - start))

{"asctime": "2021-08-10 11:49:06,773", "name": "flytekit", "levelname": "INFO", "message": "Invoking __main__.etl_pandas with inputs: {'filename': '/localdisk/tvlasova/datasets/santander_train.csv', 'columns_names': ['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52', 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66', 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77', 'var_78', 'var_79', 'var_80', 'var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89', 'var_90', 'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99', 'var_100', 'var_101', 'var_102', 'var_103', 'var_104', 'var_105', 'var_106', 'var_107', 'var_108', 'var_109', 'var_110', 'var_111', 'var_112', 'var_113', 'var_114', 'var_115', 'var_116', 'var_117', 'var_118', 'var_119', 'var_120', 'var_121', 'var_122', 'var_123', 'var_124', 'var_125', 'var_126', 'var_127', 'var_128', 'var_129', 'var_130', 'var_131', 'var_132', 'var_133', 'var_134', 'var_135', 'var_136', 'var_137', 'var_138', 'var_139', 'var_140', 'var_141', 'var_142', 'var_143', 'var_144', 'var_145', 'var_146', 'var_147', 'var_148', 'var_149', 'var_150', 'var_151', 'var_152', 'var_153', 'var_154', 'var_155', 'var_156', 'var_157', 'var_158', 'var_159', 'var_160', 'var_161', 'var_162', 'var_163', 'var_164', 'var_165', 'var_166', 'var_167', 'var_168', 'var_169', 'var_170', 'var_171', 'var_172', 'var_173', 'var_174', 'var_175', 'var_176', 'var_177', 'var_178', 'var_179', 'var_180', 'var_181', 'var_182', 'var_183', 'var_184', 'var_185', 'var_186', 'var_187', 'var_188', 'var_189', 'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195', 'var_196', 'var_197', 'var_198', 'var_199'], 'columns_types': ['object', 'int64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64'], 'etl_keys': ['t_readcsv', 't_etl', 't_connect']}"}
INFO:flytekit:Invoking __main__.etl_pandas with inputs: {'filename': '/localdisk/tvlasova/datasets/santander_train.csv', 'columns_names': ['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52', 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66', 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77', 'var_78', 'var_79', 'var_80', 'var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89', 'var_90', 'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99', 'var_100', 'var_101', 'var_102', 'var_103', 'var_104', 'var_105', 'var_106', 'var_107', 'var_108', 'var_109', 'var_110', 'var_111', 'var_112', 'var_113', 'var_114', 'var_115', 'var_116', 'var_117', 'var_118', 'var_119', 'var_120', 'var_121', 'var_122', 'var_123', 'var_124', 'var_125', 'var_126', 'var_127', 'var_128', 'var_129', 'var_130', 'var_131', 'var_132', 'var_133', 'var_134', 'var_135', 'var_136', 'var_137', 'var_138', 'var_139', 'var_140', 'var_141', 'var_142', 'var_143', 'var_144', 'var_145', 'var_146', 'var_147', 'var_148', 'var_149', 'var_150', 'var_151', 'var_152', 'var_153', 'var_154', 'var_155', 'var_156', 'var_157', 'var_158', 'var_159', 'var_160', 'var_161', 'var_162', 'var_163', 'var_164', 'var_165', 'var_166', 'var_167', 'var_168', 'var_169', 'var_170', 'var_171', 'var_172', 'var_173', 'var_174', 'var_175', 'var_176', 'var_177', 'var_178', 'var_179', 'var_180', 'var_181', 'var_182', 'var_183', 'var_184', 'var_185', 'var_186', 'var_187', 'var_188', 'var_189', 'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195', 'var_196', 'var_197', 'var_198', 'var_199'], 'columns_types': ['object', 'int64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64'], 'etl_keys': ['t_readcsv', 't_etl', 't_connect']}

{"asctime": "2021-08-10 11:50:19,118", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: (        target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \\\n0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187   \n1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208   \n2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427   \n3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428   \n4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405   \n...        ...      ...     ...      ...     ...      ...      ...     ...   \n199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709   \n199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802   \n199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555   \n199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479   \n199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839   \n\n          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \\\n0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364   \n1       16.5338  3.1468  ...       7.6421       7.7214       2.5837   \n2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704   \n3       14.9250 -5.8609  ...          NaN       4.7433       0.7178   \n4       19.2514  6.2654  ...      -1.4905       9.5214          NaN   \n...         ...     ...  ...          ...          ...          ...   \n199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901   \n199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998   \n199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032   \n199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337   \n199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276   \n\n        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \\\n0            1.6910      18.5227      -2.3978       7.8784       8.5635   \n1               NaN          NaN       2.0339       8.1267       8.7889   \n2               NaN      21.6042       3.1417      -6.5213       8.2675   \n3            1.4214      23.0347      -1.2706      -2.9275      10.2922   \n4               NaN          NaN      -1.5121       3.9267       9.5031   \n...             ...          ...          ...          ...          ...   \n199995       0.9388      18.0249      -1.7939          NaN       8.5326   \n199996          NaN      22.2717       1.7337      -2.1651       6.7419   \n199997       4.8793      23.5311      -1.5736          NaN       8.7155   \n199998      11.1178      20.4158      -0.0786          NaN      10.0342   \n199999       0.3766      15.2101      -2.4907      -2.2342       8.1857   \n\n        var_198_gt1  var_199_gt1  \n0           12.7803      -1.0914  \n1           18.3560          NaN  \n2           14.7222       0.3965  \n3           17.9697      -8.9996  \n4           17.9974      -8.8104  \n...             ...          ...  \n199995      16.6660     -17.8661  \n199996      15.9054          NaN  \n199997      13.8329          NaN  \n199998      15.5289          NaN  \n199999      12.1284          NaN  \n\n[200000 rows x 601 columns], {'t_readcsv': 4.1378264899831265, 't_etl': 68.18390418495983, 't_connect': 0.0})"}
INFO:flytekit:Task executed successfully in user level, outputs: (        target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \
0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187
1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208
2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427
3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428
4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405
...        ...      ...     ...      ...     ...      ...      ...     ...
199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709
199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802
199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555
199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479
199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839

          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \
0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364
1       16.5338  3.1468  ...       7.6421       7.7214       2.5837
2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704
3       14.9250 -5.8609  ...          NaN       4.7433       0.7178
4       19.2514  6.2654  ...      -1.4905       9.5214          NaN
...         ...     ...  ...          ...          ...          ...
199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901
199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998
199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032
199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337
199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276

        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \
0            1.6910      18.5227      -2.3978       7.8784       8.5635
1               NaN          NaN       2.0339       8.1267       8.7889
2               NaN      21.6042       3.1417      -6.5213       8.2675
3            1.4214      23.0347      -1.2706      -2.9275      10.2922
4               NaN          NaN      -1.5121       3.9267       9.5031
...             ...          ...          ...          ...          ...
199995       0.9388      18.0249      -1.7939          NaN       8.5326
199996          NaN      22.2717       1.7337      -2.1651       6.7419
199997       4.8793      23.5311      -1.5736          NaN       8.7155
199998      11.1178      20.4158      -0.0786          NaN      10.0342
199999       0.3766      15.2101      -2.4907      -2.2342       8.1857

        var_198_gt1  var_199_gt1
0           12.7803      -1.0914
1           18.3560          NaN
2           14.7222       0.3965
3           17.9697      -8.9996
4           17.9974      -8.8104
...             ...          ...
199995      16.6660     -17.8661
199996      15.9054          NaN
199997      13.8329          NaN
199998      15.5289          NaN
199999      12.1284          NaN

[200000 rows x 601 columns], {'t_readcsv': 4.1378264899831265, 't_etl': 68.18390418495983, 't_connect': 0.0})
{"asctime": "2021-08-10 11:50:24,953", "name": "flytekit", "levelname": "INFO", "message": "Invoking __main__.ml with inputs: {'ml_data':         target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \\\n0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187   \n1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208   \n2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427   \n3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428   \n4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405   \n...        ...      ...     ...      ...     ...      ...      ...     ...   \n199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709   \n199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802   \n199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555   \n199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479   \n199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839   \n\n          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \\\n0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364   \n1       16.5338  3.1468  ...       7.6421       7.7214       2.5837   \n2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704   \n3       14.9250 -5.8609  ...          NaN       4.7433       0.7178   \n4       19.2514  6.2654  ...      -1.4905       9.5214          NaN   \n...         ...     ...  ...          ...          ...          ...   \n199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901   \n199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998   \n199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032   \n199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337   \n199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276   \n\n        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \\\n0            1.6910      18.5227      -2.3978       7.8784       8.5635   \n1               NaN          NaN       2.0339       8.1267       8.7889   \n2               NaN      21.6042       3.1417      -6.5213       8.2675   \n3            1.4214      23.0347      -1.2706      -2.9275      10.2922   \n4               NaN          NaN      -1.5121       3.9267       9.5031   \n...             ...          ...          ...          ...          ...   \n199995       0.9388      18.0249      -1.7939          NaN       8.5326   \n199996          NaN      22.2717       1.7337      -2.1651       6.7419   \n199997       4.8793      23.5311      -1.5736          NaN       8.7155   \n199998      11.1178      20.4158      -0.0786          NaN      10.0342   \n199999       0.3766      15.2101      -2.4907      -2.2342       8.1857   \n\n        var_198_gt1  var_199_gt1  \n0           12.7803      -1.0914  \n1           18.3560          NaN  \n2           14.7222       0.3965  \n3           17.9697      -8.9996  \n4           17.9974      -8.8104  \n...             ...          ...  \n199995      16.6660     -17.8661  \n199996      15.9054          NaN  \n199997      13.8329          NaN  \n199998      15.5289          NaN  \n199999      12.1284          NaN  \n\n[200000 rows x 601 columns], 'target': 'target', 'ml_keys': ['t_train_test_split', 't_dmatrix', 't_training', 't_infer', 't_ml'], 'ml_score_keys': ['mse_mean', 'cod_mean', 'mse_dev']}"}

INFO:flytekit:Invoking __main__.ml with inputs: {'ml_data':         target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \
0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187
1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208
2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427
3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428
4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405
...        ...      ...     ...      ...     ...      ...      ...     ...
199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709
199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802
199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555
199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479
199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839

          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \
0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364
1       16.5338  3.1468  ...       7.6421       7.7214       2.5837
2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704
3       14.9250 -5.8609  ...          NaN       4.7433       0.7178
4       19.2514  6.2654  ...      -1.4905       9.5214          NaN
...         ...     ...  ...          ...          ...          ...
199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901
199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998
199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032
199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337
199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276

        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \
0            1.6910      18.5227      -2.3978       7.8784       8.5635
1               NaN          NaN       2.0339       8.1267       8.7889
2               NaN      21.6042       3.1417      -6.5213       8.2675
3            1.4214      23.0347      -1.2706      -2.9275      10.2922
4               NaN          NaN      -1.5121       3.9267       9.5031
...             ...          ...          ...          ...          ...
199995       0.9388      18.0249      -1.7939          NaN       8.5326
199996          NaN      22.2717       1.7337      -2.1651       6.7419
199997       4.8793      23.5311      -1.5736          NaN       8.7155
199998      11.1178      20.4158      -0.0786          NaN      10.0342
199999       0.3766      15.2101      -2.4907      -2.2342       8.1857

        var_198_gt1  var_199_gt1
0           12.7803      -1.0914
1           18.3560          NaN
2           14.7222       0.3965
3           17.9697      -8.9996
4           17.9974      -8.8104
...             ...          ...
199995      16.6660     -17.8661
199996      15.9054          NaN
199997      13.8329          NaN
199998      15.5289          NaN
199999      12.1284          NaN

[200000 rows x 601 columns], 'target': 'target', 'ml_keys': ['t_train_test_split', 't_dmatrix', 't_training', 't_infer', 't_ml'], 'ml_score_keys': ['mse_mean', 'cod_mean', 'mse_dev']}

[11:50:26] WARNING: ../src/learner.cc:573:
Parameters: { "silent" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]	eval-auc:0.53415	train-auc:0.52877
[1000]	eval-auc:0.89019	train-auc:0.90135
[2000]	eval-auc:0.90305	train-auc:0.91705
[3000]	eval-auc:0.90846	train-auc:0.92279
[4000]	eval-auc:0.91038	train-auc:0.92592
[4347]	eval-auc:0.91130	train-auc:0.92684

{"asctime": "2021-08-10 11:52:49,566", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: ({'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': 0.054204980425112737, 'cod': 0.40511252848379153}, {'t_train_test_split': 0.00017330492846667767, 't_dmatrix': 1.4182632009033114, 't_training': 0.0, 't_infer': 0.0, 't_ml': 142.77928009605967, 't_train': 142.75993236806244, 't_inference': 0.019347727997228503})"}
INFO:flytekit:Task executed successfully in user level, outputs: ({'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': 0.054204980425112737, 'cod': 0.40511252848379153}, {'t_train_test_split': 0.00017330492846667767, 't_dmatrix': 1.4182632009033114, 't_training': 0.0, 't_infer': 0.0, 't_ml': 142.77928009605967, 't_train': 142.75993236806244, 't_inference': 0.019347727997228503})

DefaultNamedTupleOutput(o0={'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': 0.054204980425112737, 'cod': 0.40511252848379153}, o1={'t_train_test_split': 0.00017330492846667767, 't_dmatrix': 1.4182632009033114, 't_training': 0.0, 't_infer': 0.0, 't_ml': 142.77928009605967, 't_train': 142.75993236806244, 't_inference': 0.019347727997228503})
--- 222.80751156806946 seconds ---

## Workflow consisting from more detalized tasks

In [8]:
@task
def load_data_pandas(
    filename: str,
    columns_names: typing.List[str],
    columns_types: typing.List[str],
    use_gzip: bool = False
) -> pd.DataFrame:
    types = None
    if columns_types:
        types = {columns_names[i]: columns_types[i] for i in range(len(columns_names))}
    return pd.read_csv(
        filename,
        names=columns_names,
        dtype=types,
        header=0,
        compression="gzip" if use_gzip else None
    )

{"asctime": "2021-08-13 11:28:42,878", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed native tuple <class 'pandas.core.frame.DataFrame'>"}

In [15]:
@task
def mse(
    y_test: pd.DataFrame,
    y_pred: pd.DataFrame
) -> float:
    return ((y_test - y_pred) ** 2).mean()


@task
def cod(
    y_test: pd.DataFrame,
    y_pred: pd.DataFrame
) -> float:
    y_bar = y_test.mean()
    total = ((y_test - y_bar) ** 2).sum()
    residuals = ((y_test - y_pred) ** 2).sum()
    return 1 - (residuals / total)

{"asctime": "2021-08-13 11:47:01,431", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed native tuple <class 'float'>"}
DEBUG:flytekit:Task returns unnamed native tuple <class 'float'>
{"asctime": "2021-08-13 11:47:01,435", "name": "flytekit", "levelname": "DEBUG", "message": "Task returns unnamed native tuple <class 'float'>"}
DEBUG:flytekit:Task returns unnamed native tuple <class 'float'>

In [10]:
@task
def split_step(
    data: pd.DataFrame,
    target: str
) -> (
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    float
):
    t0 = timer()
    train, valid = data[:-10000], data[-10000:]
    split_time = timer() - t0

    x_train = train.drop([target], axis=1)

    y_train = train[target]

    x_test = valid.drop([target], axis=1)

    y_test = valid[target]

    return x_train, y_train, x_test, y_test, split_time

In [11]:
@dynamic
def etl_pandas(
    filename: str,
    columns_names: typing.List[str],
    columns_types: typing.List[str],
    etl_keys: typing.List[str]
) -> (
    pd.DataFrame,
    typing.Dict[str, float]
):
    etl_times = {key: 0.0 for key in etl_keys}

    t0 = timer()
    train_pd = load_data_pandas(
        filename=filename,
        columns_names=columns_names,
        columns_types=columns_types,
        use_gzip=filename.endswith(".gz")
    )
    etl_times["t_readcsv"] = timer() - t0

    t_etl_begin = timer()

    for i in range(200):
        col = "var_%d" % i
        var_count = train_pd.groupby(col).agg({col: "count"})

        var_count.columns = ["%s_count" % col]
        var_count = var_count.reset_index()

        train_pd = train_pd.merge(var_count, on=col, how="left")

    for i in range(200):
        col = "var_%d" % i

        mask = train_pd["%s_count" % col] > 1
        train_pd.loc[mask, "%s_gt1" % col] = train_pd.loc[mask, col]

    train_pd = train_pd.drop(["ID_code"], axis=1)
    etl_times["t_etl"] = timer() - t_etl_begin

    return train_pd, etl_times

In [16]:
@dynamic
def ml(
    ml_data: pd.DataFrame,
    target: str,
    ml_keys: typing.List[str],
    ml_score_keys: typing.List[str] 
) -> (
    typing.Dict[str, float],
     typing.Dict[str, float]
):

    ml_times = {key: 0.0 for key in ml_keys}
    ml_scores = {key: 0.0 for key in ml_score_keys}

    x_train, y_train, x_test, y_test, ml_times["t_train_test_split"] = split_step(
        data=ml_data, target=target
    )

    t0 = timer()
    training_dmat_part = xgboost.DMatrix(data=x_train, label=y_train)
    testing_dmat_part = xgboost.DMatrix(data=x_test, label=y_test)
    ml_times["t_dmatrix"] = timer() - t0

    watchlist = [(testing_dmat_part, "eval"), (training_dmat_part, "train")]
    #     hard_code: cpu_params cannot be an input, cause values are not homogeneous
    xgb_params = {
        "objective": "binary:logistic",
        "tree_method": "hist",
        "max_depth": 1,
        "nthread": 56,
        "eta": 0.1,
        "silent": 1,
        "subsample": 0.5,
        "colsample_bytree": 0.05,
        "eval_metric": "auc",
    }

    t0 = timer()
    model = xgboost.train(
        xgb_params,
        dtrain=training_dmat_part,
        num_boost_round=10000,
        evals=watchlist,
        early_stopping_rounds=30,
        maximize=True,
        verbose_eval=1000,
    )
    ml_times["t_train"] = timer() - t0

    t0 = timer()
    yp = pd.DataFrame({"preds": model.predict(testing_dmat_part)})
    ml_times["t_inference"] = timer() - t0

    ml_scores["mse"] = mse(y_test=y_test, y_pred=yp)
    ml_scores["cod"] = cod(y_test=y_test, y_pred=yp)

    ml_times["t_ml"] += ml_times["t_train"] + ml_times["t_inference"]

    return ml_scores, ml_times

In [17]:
@workflow
def santander_ml_wf(
    filename: str = DATASET_PATH,
    columns_names: typing.List[str] = COLUMNS_NAMES,
    columns_types: typing.List[str] = COLUMNS_TYPES,
    etl_keys: typing.List[str] = ETL_KEYS,
    target: str = 'target',
    ml_keys: typing.List[str] = ML_KEYS,
    ml_score_keys: typing.List[str] = ML_SCORE_KEYS
) -> (
    typing.Dict[str, float],
     typing.Dict[str, float]
):
    df, etl_times = etl_pandas(filename=filename, columns_names=columns_names,
                               columns_types=columns_types, etl_keys=etl_keys)
    return ml(ml_data=df, target=target, ml_keys=ml_keys, ml_score_keys=ml_score_keys)

In [18]:
if __name__ == "__main__":
    start = time.time()
    print(santander_ml_wf())
    print("--- %s seconds ---" % (time.time() - start))

{"asctime": "2021-08-13 11:48:45,320", "name": "flytekit", "levelname": "INFO", "message": "Invoking __main__.etl_pandas with inputs: {'filename': '/localdisk/tvlasova/datasets/santander_train.csv', 'columns_names': ['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52', 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66', 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77', 'var_78', 'var_79', 'var_80', 'var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89', 'var_90', 'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99', 'var_100', 'var_101', 'var_102', 'var_103', 'var_104', 'var_105', 'var_106', 'var_107', 'var_108', 'var_109', 'var_110', 'var_111', 'var_112', 'var_113', 'var_114', 'var_115', 'var_116', 'var_117', 'var_118', 'var_119', 'var_120', 'var_121', 'var_122', 'var_123', 'var_124', 'var_125', 'var_126', 'var_127', 'var_128', 'var_129', 'var_130', 'var_131', 'var_132', 'var_133', 'var_134', 'var_135', 'var_136', 'var_137', 'var_138', 'var_139', 'var_140', 'var_141', 'var_142', 'var_143', 'var_144', 'var_145', 'var_146', 'var_147', 'var_148', 'var_149', 'var_150', 'var_151', 'var_152', 'var_153', 'var_154', 'var_155', 'var_156', 'var_157', 'var_158', 'var_159', 'var_160', 'var_161', 'var_162', 'var_163', 'var_164', 'var_165', 'var_166', 'var_167', 'var_168', 'var_169', 'var_170', 'var_171', 'var_172', 'var_173', 'var_174', 'var_175', 'var_176', 'var_177', 'var_178', 'var_179', 'var_180', 'var_181', 'var_182', 'var_183', 'var_184', 'var_185', 'var_186', 'var_187', 'var_188', 'var_189', 'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195', 'var_196', 'var_197', 'var_198', 'var_199'], 'columns_types': ['object', 'int64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64'], 'etl_keys': ['t_readcsv', 't_etl', 't_connect']}"}
INFO:flytekit:Invoking __main__.etl_pandas with inputs: {'filename': '/localdisk/tvlasova/datasets/santander_train.csv', 'columns_names': ['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52', 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66', 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77', 'var_78', 'var_79', 'var_80', 'var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89', 'var_90', 'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99', 'var_100', 'var_101', 'var_102', 'var_103', 'var_104', 'var_105', 'var_106', 'var_107', 'var_108', 'var_109', 'var_110', 'var_111', 'var_112', 'var_113', 'var_114', 'var_115', 'var_116', 'var_117', 'var_118', 'var_119', 'var_120', 'var_121', 'var_122', 'var_123', 'var_124', 'var_125', 'var_126', 'var_127', 'var_128', 'var_129', 'var_130', 'var_131', 'var_132', 'var_133', 'var_134', 'var_135', 'var_136', 'var_137', 'var_138', 'var_139', 'var_140', 'var_141', 'var_142', 'var_143', 'var_144', 'var_145', 'var_146', 'var_147', 'var_148', 'var_149', 'var_150', 'var_151', 'var_152', 'var_153', 'var_154', 'var_155', 'var_156', 'var_157', 'var_158', 'var_159', 'var_160', 'var_161', 'var_162', 'var_163', 'var_164', 'var_165', 'var_166', 'var_167', 'var_168', 'var_169', 'var_170', 'var_171', 'var_172', 'var_173', 'var_174', 'var_175', 'var_176', 'var_177', 'var_178', 'var_179', 'var_180', 'var_181', 'var_182', 'var_183', 'var_184', 'var_185', 'var_186', 'var_187', 'var_188', 'var_189', 'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195', 'var_196', 'var_197', 'var_198', 'var_199'], 'columns_types': ['object', 'int64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64', 'float64'], 'etl_keys': ['t_readcsv', 't_etl', 't_connect']}

{"asctime": "2021-08-13 11:48:45,323", "name": "flytekit", "levelname": "INFO", "message": "Executing Dynamic workflow, using raw inputs"}
INFO:flytekit:Executing Dynamic workflow, using raw inputs
{"asctime": "2021-08-13 11:48:45,325", "name": "flytekit", "levelname": "WARNING", "message": "task run without context - executing raw function"}
WARNING:flytekit:task run without context - executing raw function
{"asctime": "2021-08-13 11:49:57,910", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: (        target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \\\n0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187   \n1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208   \n2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427   \n3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428   \n4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405   \n...        ...      ...     ...      ...     ...      ...      ...     ...   \n199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709   \n199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802   \n199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555   \n199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479   \n199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839   \n\n          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \\\n0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364   \n1       16.5338  3.1468  ...       7.6421       7.7214       2.5837   \n2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704   \n3       14.9250 -5.8609  ...          NaN       4.7433       0.7178   \n4       19.2514  6.2654  ...      -1.4905       9.5214          NaN   \n...         ...     ...  ...          ...          ...          ...   \n199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901   \n199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998   \n199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032   \n199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337   \n199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276   \n\n        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \\\n0            1.6910      18.5227      -2.3978       7.8784       8.5635   \n1               NaN          NaN       2.0339       8.1267       8.7889   \n2               NaN      21.6042       3.1417      -6.5213       8.2675   \n3            1.4214      23.0347      -1.2706      -2.9275      10.2922   \n4               NaN          NaN      -1.5121       3.9267       9.5031   \n...             ...          ...          ...          ...          ...   \n199995       0.9388      18.0249      -1.7939          NaN       8.5326   \n199996          NaN      22.2717       1.7337      -2.1651       6.7419   \n199997       4.8793      23.5311      -1.5736          NaN       8.7155   \n199998      11.1178      20.4158      -0.0786          NaN      10.0342   \n199999       0.3766      15.2101      -2.4907      -2.2342       8.1857   \n\n        var_198_gt1  var_199_gt1  \n0           12.7803      -1.0914  \n1           18.3560          NaN  \n2           14.7222       0.3965  \n3           17.9697      -8.9996  \n4           17.9974      -8.8104  \n...             ...          ...  \n199995      16.6660     -17.8661  \n199996      15.9054          NaN  \n199997      13.8329          NaN  \n199998      15.5289          NaN  \n199999      12.1284          NaN  \n\n[200000 rows x 601 columns], {'t_readcsv': 4.177580547053367, 't_etl': 68.38774566189386, 't_connect': 0.0})"}
INFO:flytekit:Task executed successfully in user level, outputs: (        target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \
0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187
1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208
2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427
3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428
4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405
...        ...      ...     ...      ...     ...      ...      ...     ...
199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709
199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802
199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555
199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479
199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839

          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \
0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364
1       16.5338  3.1468  ...       7.6421       7.7214       2.5837
2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704
3       14.9250 -5.8609  ...          NaN       4.7433       0.7178
4       19.2514  6.2654  ...      -1.4905       9.5214          NaN
...         ...     ...  ...          ...          ...          ...
199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901
199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998
199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032
199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337
199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276

        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \
0            1.6910      18.5227      -2.3978       7.8784       8.5635
1               NaN          NaN       2.0339       8.1267       8.7889
2               NaN      21.6042       3.1417      -6.5213       8.2675
3            1.4214      23.0347      -1.2706      -2.9275      10.2922
4               NaN          NaN      -1.5121       3.9267       9.5031
...             ...          ...          ...          ...          ...
199995       0.9388      18.0249      -1.7939          NaN       8.5326
199996          NaN      22.2717       1.7337      -2.1651       6.7419
199997       4.8793      23.5311      -1.5736          NaN       8.7155
199998      11.1178      20.4158      -0.0786          NaN      10.0342
199999       0.3766      15.2101      -2.4907      -2.2342       8.1857

        var_198_gt1  var_199_gt1
0           12.7803      -1.0914
1           18.3560          NaN
2           14.7222       0.3965
3           17.9697      -8.9996
4           17.9974      -8.8104
...             ...          ...
199995      16.6660     -17.8661
199996      15.9054          NaN
199997      13.8329          NaN
199998      15.5289          NaN
199999      12.1284          NaN

[200000 rows x 601 columns], {'t_readcsv': 4.177580547053367, 't_etl': 68.38774566189386, 't_connect': 0.0})
{"asctime": "2021-08-13 11:50:03,602", "name": "flytekit", "levelname": "INFO", "message": "Invoking __main__.ml with inputs: {'ml_data':         target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \\\n0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187   \n1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208   \n2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427   \n3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428   \n4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405   \n...        ...      ...     ...      ...     ...      ...      ...     ...   \n199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709   \n199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802   \n199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555   \n199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479   \n199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839   \n\n          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \\\n0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364   \n1       16.5338  3.1468  ...       7.6421       7.7214       2.5837   \n2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704   \n3       14.9250 -5.8609  ...          NaN       4.7433       0.7178   \n4       19.2514  6.2654  ...      -1.4905       9.5214          NaN   \n...         ...     ...  ...          ...          ...          ...   \n199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901   \n199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998   \n199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032   \n199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337   \n199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276   \n\n        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \\\n0            1.6910      18.5227      -2.3978       7.8784       8.5635   \n1               NaN          NaN       2.0339       8.1267       8.7889   \n2               NaN      21.6042       3.1417      -6.5213       8.2675   \n3            1.4214      23.0347      -1.2706      -2.9275      10.2922   \n4               NaN          NaN      -1.5121       3.9267       9.5031   \n...             ...          ...          ...          ...          ...   \n199995       0.9388      18.0249      -1.7939          NaN       8.5326   \n199996          NaN      22.2717       1.7337      -2.1651       6.7419   \n199997       4.8793      23.5311      -1.5736          NaN       8.7155   \n199998      11.1178      20.4158      -0.0786          NaN      10.0342   \n199999       0.3766      15.2101      -2.4907      -2.2342       8.1857   \n\n        var_198_gt1  var_199_gt1  \n0           12.7803      -1.0914  \n1           18.3560          NaN  \n2           14.7222       0.3965  \n3           17.9697      -8.9996  \n4           17.9974      -8.8104  \n...             ...          ...  \n199995      16.6660     -17.8661  \n199996      15.9054          NaN  \n199997      13.8329          NaN  \n199998      15.5289          NaN  \n199999      12.1284          NaN  \n\n[200000 rows x 601 columns], 'target': 'target', 'ml_keys': ['t_train_test_split', 't_dmatrix', 't_training', 't_infer', 't_ml'], 'ml_score_keys': ['mse_mean', 'cod_mean', 'mse_dev']}"}

INFO:flytekit:Invoking __main__.ml with inputs: {'ml_data':         target    var_0   var_1    var_2   var_3    var_4    var_5   var_6  \
0            0   8.9255 -6.7863  11.9081  5.0930  11.4607  -9.2834  5.1187
1            0  11.5006 -4.1473  13.8588  5.3890  12.3622   7.0433  5.6208
2            0   8.6093 -2.7457  12.0805  7.8928  10.5825  -9.0837  6.9427
3            0  11.0604 -2.1518   8.9522  7.1957  12.5846  -1.8361  5.8428
4            0   9.8369 -1.4834  12.8746  6.6375  12.2772   2.4486  5.9405
...        ...      ...     ...      ...     ...      ...      ...     ...
199995       0  11.4880 -0.4956   8.2622  3.5142  10.3404  11.6081  5.6709
199996       0   4.9149 -2.4484  16.7052  6.6345   8.3096 -10.5628  5.8802
199997       0  11.2232 -5.0518  10.5127  5.6456   9.3410  -5.4086  4.5555
199998       0   9.7148 -8.6098  13.6104  5.7930  12.5173   0.5339  6.0479
199999       0  10.8762 -5.7105  12.1183  8.0328  11.5577   0.3488  5.2839

          var_7   var_8  ...  var_190_gt1  var_191_gt1  var_192_gt1  \
0       18.6266 -4.9200  ...       4.4354       3.9642       3.1364
1       16.5338  3.1468  ...       7.6421       7.7214       2.5837
2       14.6155 -4.9193  ...       2.9057       9.7905       1.6704
3       14.9250 -5.8609  ...          NaN       4.7433       0.7178
4       19.2514  6.2654  ...      -1.4905       9.5214          NaN
...         ...     ...  ...          ...          ...          ...
199995  15.1516 -0.6209  ...       6.1415          NaN       3.9901
199996  21.5940 -3.6797  ...          NaN       4.6549       0.6998
199997  21.5571  0.1202  ...       4.0651       5.4414       3.1032
199998  17.0152 -2.1926  ...       2.6840       8.6587       2.7337
199999  15.2058 -0.4541  ...       8.9842       1.6893       0.1276

        var_193_gt1  var_194_gt1  var_195_gt1  var_196_gt1  var_197_gt1  \
0            1.6910      18.5227      -2.3978       7.8784       8.5635
1               NaN          NaN       2.0339       8.1267       8.7889
2               NaN      21.6042       3.1417      -6.5213       8.2675
3            1.4214      23.0347      -1.2706      -2.9275      10.2922
4               NaN          NaN      -1.5121       3.9267       9.5031
...             ...          ...          ...          ...          ...
199995       0.9388      18.0249      -1.7939          NaN       8.5326
199996          NaN      22.2717       1.7337      -2.1651       6.7419
199997       4.8793      23.5311      -1.5736          NaN       8.7155
199998      11.1178      20.4158      -0.0786          NaN      10.0342
199999       0.3766      15.2101      -2.4907      -2.2342       8.1857

        var_198_gt1  var_199_gt1
0           12.7803      -1.0914
1           18.3560          NaN
2           14.7222       0.3965
3           17.9697      -8.9996
4           17.9974      -8.8104
...             ...          ...
199995      16.6660     -17.8661
199996      15.9054          NaN
199997      13.8329          NaN
199998      15.5289          NaN
199999      12.1284          NaN

[200000 rows x 601 columns], 'target': 'target', 'ml_keys': ['t_train_test_split', 't_dmatrix', 't_training', 't_infer', 't_ml'], 'ml_score_keys': ['mse_mean', 'cod_mean', 'mse_dev']}
{"asctime": "2021-08-13 11:50:03,604", "name": "flytekit", "levelname": "INFO", "message": "Executing Dynamic workflow, using raw inputs"}
INFO:flytekit:Executing Dynamic workflow, using raw inputs
{"asctime": "2021-08-13 11:50:03,604", "name": "flytekit", "levelname": "WARNING", "message": "task run without context - executing raw function"}
WARNING:flytekit:task run without context - executing raw function

[11:50:05] WARNING: ../src/learner.cc:573:
Parameters: { "silent" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]	eval-auc:0.53415	train-auc:0.52877
[1000]	eval-auc:0.89019	train-auc:0.90135
[2000]	eval-auc:0.90305	train-auc:0.91705
[3000]	eval-auc:0.90846	train-auc:0.92279
[4000]	eval-auc:0.91038	train-auc:0.92592
[4348]	eval-auc:0.91127	train-auc:0.92682

{"asctime": "2021-08-13 11:52:19,948", "name": "flytekit", "levelname": "WARNING", "message": "task run without context - executing raw function"}
WARNING:flytekit:task run without context - executing raw function
{"asctime": "2021-08-13 11:52:21,401", "name": "flytekit", "levelname": "WARNING", "message": "task run without context - executing raw function"}
WARNING:flytekit:task run without context - executing raw function
{"asctime": "2021-08-13 11:52:22,860", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: ({'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': preds    NaN\n190000   NaN\n190001   NaN\n190002   NaN\n190003   NaN\n          ..\n199995   NaN\n199996   NaN\n199997   NaN\n199998   NaN\n199999   NaN\nLength: 10001, dtype: float64, 'cod': preds     1.0\n190000    1.0\n190001    1.0\n190002    1.0\n190003    1.0\n         ... \n199995    1.0\n199996    1.0\n199997    1.0\n199998    1.0\n199999    1.0\nLength: 10001, dtype: float64}, {'t_train_test_split': 8.55959951877594e-05, 't_dmatrix': 1.1444270720239729, 't_training': 0.0, 't_infer': 0.0, 't_ml': 134.85849454486743, 't_train': 134.8375682339538, 't_inference': 0.02092631091363728})"}
INFO:flytekit:Task executed successfully in user level, outputs: ({'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': preds    NaN
190000   NaN
190001   NaN
190002   NaN
190003   NaN
          ..
199995   NaN
199996   NaN
199997   NaN
199998   NaN
199999   NaN
Length: 10001, dtype: float64, 'cod': preds     1.0
190000    1.0
190001    1.0
190002    1.0
190003    1.0
         ...
199995    1.0
199996    1.0
199997    1.0
199998    1.0
199999    1.0
Length: 10001, dtype: float64}, {'t_train_test_split': 8.55959951877594e-05, 't_dmatrix': 1.1444270720239729, 't_training': 0.0, 't_infer': 0.0, 't_ml': 134.85849454486743, 't_train': 134.8375682339538, 't_inference': 0.02092631091363728})

DefaultNamedTupleOutput(o0={'mse_mean': 0.0, 'cod_mean': 0.0, 'mse_dev': 0.0, 'mse': preds    NaN
190000   NaN
190001   NaN
190002   NaN
190003   NaN
          ..
199995   NaN
199996   NaN
199997   NaN
199998   NaN
199999   NaN
Length: 10001, dtype: float64, 'cod': preds     1.0
190000    1.0
190001    1.0
190002    1.0
190003    1.0
         ...
199995    1.0
199996    1.0
199997    1.0
199998    1.0
199999    1.0
Length: 10001, dtype: float64}, o1={'t_train_test_split': 8.55959951877594e-05, 't_dmatrix': 1.1444270720239729, 't_training': 0.0, 't_infer': 0.0, 't_ml': 134.85849454486743, 't_train': 134.8375682339538, 't_inference': 0.02092631091363728})
--- 217.5518991947174 seconds ---